Pipeline 

# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Teste 
    - run: covarage run app_teste.py

    - name: Relatorio do teste
    - run: covarage report -a

    - name: Deploy no EC2 - AWS
      run: |
           echo "Conectando no EC2"
           echo "${{secrets.AWS_KEY_VENV}}" > private_key && chmod 600 private key
           ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-44-223-202-28.compute-1.amazonaws.com "
                  cd flask_de_criazin/;git pull;./executar.sh"
